name: Full project build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  frontend-build:
     
     # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 19.6.0
      uses: actions/setup-node@v1
      with:
        node-version: 19.6.0
    - name: Install dependencies
      working-directory: frontend
      run: npm install
    - name: Lint
      working-directory: frontend
      run: npm run lint
    - name: Build
      working-directory: frontend
      run: npm run build -- --prod
    - name: Test
      working-directory: frontend
      run: npm test -- --configuration=ci
    - name: E2E
      working-directory: frontend
      run: npm run e2e -- --configuration=ci
      
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        working-directory: backend
        run: mvn clean install

      - name: Run tests
        working-directory: backend
        run: mvn test
